### ISSUE TITLE
Ники

### ISSUE THREAD

**Issue by Lanaken** [bmstu-iu9/utp2018-7-forum#10]
Добавьте пожалуйста к участникам проекта их ники.

**Comment by Mazdaywik** [comment]
Ник можно увидеть, если навести мышкой на гиперссылку — появляется в строке состояния браузера. Но, согласен, явно перечисленные ники читабельнее (и нам с @alex-qrcs будет проще проверять).

**Comment by SpeedyGonzaless** [comment]
сделано
