### ISSUE TITLE
Не получается создать тему

### ISSUE THREAD

**Issue by Lanaken** [bmstu-iu9/utp2018-7-forum#7]
Ни в одном из разделов не получилось создать тему. Каждый раз просто пропадал весь текст.
Использовался Google Chrome

**Comment by SpeedyGonzaless** [comment]
все еще имеется данная проблема?

**Comment by Lanaken** [comment]
Да

**Comment by SpeedyGonzaless** [comment]
![image](https://user-images.githubusercontent.com/40829475/45265375-a26a6600-b452-11e8-8a4d-794dc9e2da81.png)
а какие у вас cookie?

**Comment by Lanaken** [comment]
Прошу прощения, проб
